elections/Cargo.toml
elections/src/constants.rs
elections/src/lib.rs
elections/src/proposal.rs

+ add unit tests for the proposal creation, voting and admin_assert
+ minor naming fixes

add unit tests for elections

---

elections/src/ext.rs
elections/src/integration_tests/workspaces.rs
elections/src/lib.rs

+ add iah sbt check in vote
+ update the test
+ rename `creat_proposal` -> `create_proposal`
Additionally:
+ add check for the expired tokens 
+ add a integration test for the expired_token case

add iah sbt check in vote

---

nominations/src/lib.rs

+ add unit tests
+ add check for self upvotes
+ bug fix in `self_nominate`

add unit tests

---

nominations/src/ext.rs
nominations/src/integration_tests/workspaces.rs
nominations/src/lib.rs

+ update existing tests 
+ add new tests scenarios to cover all the cross-contract-calls in nominations
+ bug fix

integration test update for nominations

---

elections/tests/iah.rs
nominations/src/integration_tests/workspaces.rs
nominations/src/lib.rs
nominations/src/storage.rs

+ fix unit tests
+ additional integration test for double upvote and upvote after self revoke (it was moved to integrations rather that unit tests since the check now is done in the callback)
+ bug fix for the upvotes

nominations_improvments

---

elections/README.md
elections/src/proposal.rs
elections/tests/iah.rs

+ test case that checks the state change after vote

State change test

---

elections/src/events.rs
elections/src/lib.rs

+ add revoke_vote event 
+ add unit tests

add revoke vote event; add unit tests

---

elections/src/constants.rs
elections/src/ext.rs
elections/src/lib.rs
elections/src/proposal.rs
elections/src/storage.rs
elections/src/view.rs

+ add `users_sbt` map to track sbts with which users has voted
+ add `user_votes`  that returns all the votes from the user
+ add `has_voted_on_all_proposals` view method that returns true/false
+ unit tests
+ increase deposit

Query vote

---

elections/src/lib.rs
elections/src/proposal.rs
elections/src/view.rs

+ add `winners_by_house` view method
+ unit test
+ change `min_candidate_support` from `u32` to `u64`
+  add `is_past_cooldown` method
+ update `user_votes` method to iterate from `1` rather than from `0` (the first proposal index is 1)
+ add `mock_proposal_and_votes` method to test module

winners_by_house view method

---

elections/src/constants.rs
elections/src/errors.rs
elections/src/ext.rs
elections/src/lib.rs
elections/src/storage.rs
elections/tests/iah.rs

+ rename `revoke_vote` to `admin_revoke_vote`
+ add new method  `revoke_vote` that allows everyone to revoke votes from blacklisted accounts 
+ update unit test
TODO:

add revoke_vote by everyone

---

elections/src/lib.rs

+ calculate how much tokens user has bonded and keep track of it 
+ add unit test

add check if user already bonded

---

elections/CHANGELOG.md
elections/README.md
elections/src/lib.rs

+ add list of all new methods to the change log
+ update docs

add release notes

---

elections/CHANGELOG.md
elections/src/lib.rs
elections/src/view.rs

+ bug fix in the amount of winners returned by `winners_by_house`
+ add unit test for it
+ update changelog

Bug fix winner_by_house

---

.github/workflows/rust.yml
Cargo.toml
congress/Cargo.toml
congress/tests/integration.rs
elections/Cargo.toml
elections/tests/iah.rs
integrations/Cargo.toml
integrations/src/lib.rs
nominations/Cargo.toml
nominations/tests/workspaces.rs

- rename `workspaces` to `near-workspaces`
- update the code

rename workspaces to near-workspaces

---

elections/CHANGELOG.md
elections/Cargo.toml
elections/src/lib.rs
elections/src/migrate.rs
elections/src/storage.rs
elections/src/view.rs
elections/tests/iah.rs

- add `class_metadata` field
- view method `class_metadata`
- method for admin `admin_set_class_metadata`
- migration 
- migration integration test 
- unit tests

add support for class_metadata

---

voting_body/src/lib.rs
voting_body/src/view.rs

- add reversed option to`get_proposal`
- unit test

Voting Body: add reversed to get_proposalas

---

voting_body/Cargo.toml
voting_body/src/ext.rs
voting_body/src/lib.rs
voting_body/src/proposal.rs

+ add concrete proposal types
+ remove used function from test `create_all_props`

concrete proposals instead of function calls

---

voting_body/src/errors.rs
voting_body/src/lib.rs
voting_body/src/types.rs

+ add check if registry is calling the vote function
+ update existing unit tests 
+ add unit test for the panic

Human gated vote

---

voting_body/README.md

+ add documentation about proposal kinds in `README`

Document proposals

---

voting_body/README.md
voting_body/src/proposal.rs

+ add `dao` argument to `ApproveBudget` to enable other DAOs to use the voting_body contract

add dao as an argument to ApproveBudget

---

congress/CHANGELOG.md
congress/src/lib.rs
congress/src/migrate.rs
congress/src/view.rs
congress/tests/integration.rs

+ add `members_len` field
+ view method `members_len()`
+ unit test
+ migration
+ integration test for migration

add members_len field

---

voting_body/README.md

- document vb events in `README`

document vb events

---

congress/tests/integration.rs
integrations/Cargo.toml
integrations/src/lib.rs
voting_body/Cargo.toml
voting_body/src/lib.rs
voting_body/tests/integration.rs

+ integration tests for vb
+ move `instantiate_congress` to common

Integration vb

---

congress/src/lib.rs

All members should be able to make a `FunctionCall` perm

congress: self auth to extend members permissions to do FunCall
